-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    available BOOLEAN DEFAULT TRUE
);

CREATE TABLE Purchases (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    time_purchased TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE Wishes (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    time_added TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE Address (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    streetaddresslineone VARCHAR(255) NOT NULL,
    streetaddresslinetwo VARCHAR(255),
    cityname VARCHAR(255) NOT NULL,
    state VARCHAR(50) NOT NULL,
    country VARCHAR(50) NOT NULL,
    zipcode VARCHAR(20) NOT NULL,
    addresstype VARCHAR(20) NOT NULL -- Residential or Business
);


CREATE TABLE Sellers (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    addressid INT NOT NULL REFERENCES Address(id),
    sellername VARCHAR(255) NOT NULL,
    selleremail VARCHAR(255) NOT NULL,
    sellerphone VARCHAR(20) NOT NULL,
    sellerstatus VARCHAR(20) NOT NULL -- Active, Discontinous
);

CREATE TABLE Accounts (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) UNIQUE NOT NULL,
    acctcreationdate TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    sellerid INT REFERENCES Sellers(id), 
    accountbalance DECIMAL(12,2),
    addressid INT REFERENCES Address(id),
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE Loyalty (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    accountid INT NOT NULL REFERENCES Accounts(id),
    alltime_spend DECIMAL(12,2) NOT NULL,
    ytd_spend DECIMAL(12,2) NOT NULL,
    loyaltystatus VARCHAR(20) NOT NULL, -- Silver, Gold, Platinum, Diamond
    loyaltypoints DECIMAL(12,2) NOT NULL
);

CREATE TABLE Purchases_2 (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    accountid INT NOT NULL REFERENCES Accounts(id),
    total DECIMAL(12,2) NOT NULL,
    time_purchased TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    addressid INT NOT NULL REFERENCES Address(id)
);

CREATE TABLE ProductCategories (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category VARCHAR(255) NOT NULL,
    subcategory VARCHAR(255) NOT NULL
);

CREATE TABLE Products_2 (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL, -- Eventually after this step, we will see an image column
    sellerid INT NOT NULL REFERENCES Sellers(id),
    price DECIMAL(12,2) NOT NULL,
    categoryid INT NOT NULL REFERENCES ProductCategories(id),
    status BOOLEAN DEFAULT TRUE, -- Active, Inactive
    image VARCHAR(255) -- name of the image file
);

CREATE TABLE Events (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL, -- Activity, Holiday, Party
    categoryid INT NOT NULL REFERENCES ProductCategories(id)
);

CREATE TABLE Seller_Reviews (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    accountid INT NOT NULL REFERENCES Accounts(id),
    sellerid INT NOT NULL REFERENCES Sellers(id),
    rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment VARCHAR(500),
    time_submitted TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE Cart (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    accountid INT NOT NULL REFERENCES Accounts(id),
    productid INT NOT NULL REFERENCES Products_2(id),
    quantity INT NOT NULL
);

CREATE TABLE Wishlist_2 (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    accountid INT NOT NULL REFERENCES Accounts(id),
    productid INT NOT NULL REFERENCES Products_2(id),
    time_added TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE LineItem (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    purchaseid INT NOT NULL REFERENCES Purchases_2(id),
    linenumber INT NOT NULL,
    productid INT NOT NULL REFERENCES Products_2(id),
    qty INT NOT NULL,
    sellerid INT NOT NULL REFERENCES Sellers(id),
    inprocesstimestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    fulfillmenttimestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE Inventory (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    productid INT NOT NULL REFERENCES Products_2(id),
    sellerid INT NOT NULL REFERENCES Sellers(id),
    qtyinstock INT NOT NULL,
    qtyinprocess INT NOT NULL,
    qtyavailable INT NOT NULL,
    timeadded TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE Product_Reviews (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    accountid INT NOT NULL REFERENCES Accounts(id),
    productid INT NOT NULL REFERENCES Products_2(id),
    comment VARCHAR(500),
    rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    time_submitted TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);  

